// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	model "github.com/jumia-challenger/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ReadPhoneNumbers provides a mock function with given fields:
func (_m *Service) ReadPhoneNumbers() ([]model.PhoneNumber, error) {
	ret := _m.Called()

	var r0 []model.PhoneNumber
	if rf, ok := ret.Get(0).(func() []model.PhoneNumber); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PhoneNumber)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
